name: Build and Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t z4lit0/fiapcloudgamingdockrepo:latest .

      - name: Push Docker image
        run: docker push z4lit0/fiapcloudgamingdockrepo:latest
        
  deploy-to-ec2:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull z4lit0/fiapcloudgamingdockrepo:latest
            docker stop fcg.api || true
            docker rm fcg.api || true
            docker run -d --name fcg.api -p 5001:8080 z4lit0/fiapcloudgamingdockrepo:latest
